--- 
- name: Update and upgrade apt packages using shell module
  become: yes
  gather_facts: false
  tasks:
    - name: Update all packages
      apt:
        upgrade: dist
        update_cache: yes
