--- 
- name: Update and upgrade apt packages using shell module
  hosts: farm_a
  become: true
  gather_facts: false
  tasks:
    - name: Update all packages
      apt:
        upgrade: dist
        update_cache: yes
