---
- name: Get version details
  hosts: farm_a
  gather_facts: yes
  become: false
  tasks:
  - name: Distribution
  # debug: msg=" distribution {{ ansible_distribution }} - os_family {{ ansible_os_family}} - distribution_version {{ansible_distribution_version}} - distribution_major_version {{ ansible_distribution_major_version }}"
    debug: msg=" {{ ansible_facts['distribution'] }}"


  #become: false
  #gather_facts: false
  #tasks:
  #- name: System details
  #  debug: msg="{{ item }}"
  #  with_items: 
  #  - "{{ ansible_distribution }}"
  #  - "{{ ansible_distribution_version }}"
  #  - "{{ ansible_distribution_major_version }}"