---
- name: Get version details
  hosts: farm_a
  become: false
  gather_facts: false
  tasks:
    - name: System details
      debug:
        msg: "{{ item }}"
      loop:
        - "{{ ansible_facts['distribution'] }}"
        - "{{ ansible_facts['distribution_version'] }}"
        - "{{ ansible_facts['distribution_major_version'] }}"